//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public System.Guid Id { get; set; }
        public string Gender { get; set; }
        public string FirstName { get; set; }
        public string Email { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public bool AllowConsentForMarketing { get; set; }
        public System.Guid NewsletterId { get; set; }
    
        public virtual Newsletter Newsletter { get; set; }
    }
}
